[package]
name = "ninja_journal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
rustc-serialize = "0.3.24"
hex = "0.4.3"
aes="0.7.5"
block-modes="0.8.1"
hex-literal="0.3.3"